import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";

const ibmPlexSans = IBM_Plex_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
});

const ibmPlexSerif = IBM_Plex_Serif({
	weight: ["200", "400", "600"],
	style: ["normal", "italic"],
	variable: "--font-serif",
	subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
	weight: "400",
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} ${ibmPlexSerif.variable}`}
			>
				<Navbar
					links={[
						{ label: "Sign up", href: "/signup" },
						{ label: "Log in", href: "/login" },
					]}
				/>
				{children}
			</body>
		</html>
	);
}
